//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Dong_DBEntities : DbContext
    {
        public Dong_DBEntities()
            : base("name=Dong_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGoods> tblGoods { get; set; }
        public virtual DbSet<tblGoodsType> tblGoodsType { get; set; }
        public virtual DbSet<tblGroup> tblGroup { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserGroup> tblUserGroup { get; set; }
    
        public virtual int PRC_CHECK_OUT(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_CHECK_OUT", criteriaParameter);
        }
    
        public virtual int PRC_EXPIRE_GOODS(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_EXPIRE_GOODS", criteriaParameter);
        }
    
        public virtual ObjectResult<PRC_GET_GROUP_LIST_Result> PRC_GET_GROUP_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRC_GET_GROUP_LIST_Result>("PRC_GET_GROUP_LIST");
        }
    
        public virtual ObjectResult<PRC_GET_GROUP_MEMBER_Result> PRC_GET_GROUP_MEMBER(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRC_GET_GROUP_MEMBER_Result>("PRC_GET_GROUP_MEMBER", groupIDParameter);
        }
    
        public virtual ObjectResult<PRC_GET_GROUP_TRANSACTION_Result> PRC_GET_GROUP_TRANSACTION(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRC_GET_GROUP_TRANSACTION_Result>("PRC_GET_GROUP_TRANSACTION", criteriaParameter);
        }
    
        public virtual ObjectResult<PRC_DELETE_TRANSACTION_Result> PRC_DELETE_TRANSACTION(Nullable<int> goodId, Nullable<int> groupId)
        {
            var goodIdParameter = goodId.HasValue ?
                new ObjectParameter("GoodId", goodId) :
                new ObjectParameter("GoodId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRC_DELETE_TRANSACTION_Result>("PRC_DELETE_TRANSACTION", goodIdParameter, groupIdParameter);
        }
    }
}
